discord:
  token: "BOT_TOKEN_HERE"
  channel-id: "CHANNEL_ID_HERE"


format:
  minecraft-to-discord: "**[Minecraft]** {player}: {message}"
  discord-to-minecraft: "**[Discord]** {user}: {message}"
  join: "ðŸŸ¢ **{player}** has joined the server"
  leave: "ðŸ”´ **{player}** has left the server"
